const ideas={
  courtyard:{title:"Courtyard House",month:"Mar",category:"Architecture",body:"A quiet home arranged around an open square of sky. The courtyard is not an absence—it is the room that gives every other room its breath.",quote:"Let the weather become part of the architecture.",status:"In bloom",health:88,color:"linear-gradient(145deg,#c8b797,#71866b)"},
  thresholds:{title:"Soft Thresholds",month:"May",category:"Material study",body:"A study of curtains, screens, shadows and perforated brick—ways to separate spaces without making a hard boundary.",quote:"A threshold can invite before it divides.",status:"Growing",health:67,color:"linear-gradient(145deg,#d3bd9c,#9d8266)"},
  living:{title:"The Living Archive",month:"Sep",category:"Research",body:"A public archive that changes with its visitors: drawings accumulate, stories are pinned up, and the building remembers each season.",quote:"Buildings can hold memory without becoming monuments.",status:"Bearing fruit",health:94,color:"linear-gradient(145deg,#b5b08c,#64795d)"},
  terracotta:{title:"Terracotta Light",month:"Jun",category:"Material study",body:"A porous terracotta skin that filters the hard afternoon sun into warm fragments. The idea is promising, but its structural system is unresolved.",quote:"Return with a section sketch before this thought fades.",status:"Needs care",health:32,fragile:true,color:"linear-gradient(145deg,#c99a73,#8e755e)"},
  rain:{title:"Rooms for Rain",month:"Aug",category:"Landscape",body:"Courtyards, channels and planted edges designed around the arrival of monsoon rain—not as drainage infrastructure, but as inhabitable weather.",quote:"Design the sound of water as carefully as its path.",status:"Growing",health:73,color:"linear-gradient(145deg,#aebeb6,#637f78)"}
};
const positions=[[36,59],[49,35],[61,65],[74,48],[32,63],[54,28],[78,66],[66,23]];
const panel=document.querySelector('#detailPanel'),journal=document.querySelector('#journalPanel'),toast=document.querySelector('#toast');let current=null,activeMonth=null;
const stored=()=>{try{return JSON.parse(localStorage.getItem('anushka-ideas')||'[]')}catch{return[]}};
function showToast(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
function escapeText(value){const d=document.createElement('div');d.textContent=value||'';return d.innerHTML}
function openIdea(id){const idea=ideas[id];if(!idea)return;current=id;document.querySelector('#detailTitle').textContent=idea.title;document.querySelector('#detailMeta').textContent=`${idea.category.toUpperCase()} · ${idea.month.toUpperCase()} 2026`;document.querySelector('#detailBody').textContent=idea.body||"A newly planted thought. Return with a sketch, a note, or a question and let it grow.";document.querySelector('#detailQuote').textContent=idea.quote||"Every finished place began as an unfinished thought.";document.querySelector('#statusText').textContent=idea.status;document.querySelector('#statusFill').style.width=idea.health+'%';const img=document.querySelector('#detailImage');img.style.background=idea.photo?`url(${idea.photo}) center/cover`:idea.color;panel.classList.add('open');panel.setAttribute('aria-hidden','false')}
function closeIdea(){panel.classList.remove('open');panel.setAttribute('aria-hidden','true')}
function bindPlant(node){node.addEventListener('click',()=>openIdea(node.dataset.id))}
function plantSavedIdeas(){stored().forEach((raw,index)=>{const item={...raw,month:raw.month||'Mar',body:raw.body||raw.note||''},id=`saved-${index}`,pos=positions[index%positions.length];ideas[id]={...item,status:item.fragile?'Needs care':'Just planted',health:item.fragile?42:58,color:"linear-gradient(145deg,#cdbb91,#78906a)"};if(document.querySelector(`[data-id="${id}"]`))return;const node=document.createElement('button');node.className=`plant seedling custom newly-planted${item.fragile?' fragile-plant':''}`;node.dataset.id=id;node.dataset.month=item.month;node.style.setProperty('--x',pos[0]+'%');node.style.setProperty('--y',pos[1]+'%');node.setAttribute('aria-label',`Open ${item.title} idea`);node.innerHTML=`${item.fragile?'<span class="care-ring"></span>':''}<span class="plant-art"></span><span class="plant-label"><b>${escapeText(item.title)}</b><small>${escapeText(item.category)} · ${item.month}</small></span>`;document.querySelector('#garden').appendChild(node);bindPlant(node)})}
function renderJournal(filter='all'){const grid=document.querySelector('#journalGrid');grid.innerHTML='';Object.entries(ideas).filter(([,idea])=>filter==='all'||idea.fragile).forEach(([id,idea])=>{const card=document.createElement('button');card.className='journal-card';const bg=idea.photo?`background-image:url(${idea.photo})`:`background:${idea.color}`;card.innerHTML=`<div class="journal-thumb" data-month="${idea.month} 2026" style="${bg}"></div><h3>${escapeText(idea.title)}</h3><p>${escapeText(idea.category)} · ${escapeText((idea.body||'A newly planted thought.').slice(0,95))}${(idea.body||'').length>95?'…':''}</p><span class="card-status">${escapeText(idea.status)}</span>`;card.addEventListener('click',()=>{journal.classList.remove('open');openIdea(id)});grid.appendChild(card)});const count=Object.keys(ideas).length;document.querySelector('#journalCount').textContent=count;document.querySelector('#ideaCount').textContent=count}
document.querySelectorAll('.plant').forEach(bindPlant);plantSavedIdeas();renderJournal();
document.querySelector('#closePanel').addEventListener('click',closeIdea);document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeIdea();journal.classList.remove('open')}});
document.querySelectorAll('.mode-switch button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.mode-switch button').forEach(b=>b.classList.toggle('active',b===btn));document.querySelector('#garden').classList.toggle('gardener-mode',btn.dataset.mode==='garden');showToast(btn.dataset.mode==='garden'?'Gardener mode: plant health is visible':'Explore mode: wander freely')}));
document.querySelectorAll('.month-path button').forEach(btn=>btn.addEventListener('click',()=>{const next=activeMonth===btn.textContent?null:btn.textContent;activeMonth=next;document.querySelectorAll('.month-path button').forEach(b=>b.classList.toggle('active',b.textContent===next));document.querySelectorAll('.plant').forEach(p=>p.classList.toggle('month-muted',!!next&&p.dataset.month!==next));showToast(next?`${next} stories are now in focus`:'The whole year is visible')}));
function openJournal(){closeIdea();renderJournal();journal.classList.add('open');journal.setAttribute('aria-hidden','false')}document.querySelector('#openJournal').addEventListener('click',openJournal);document.querySelector('#panelJournal').addEventListener('click',openJournal);document.querySelector('#closeJournal').addEventListener('click',()=>{journal.classList.remove('open');journal.setAttribute('aria-hidden','true')});document.querySelectorAll('.journal-controls button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.journal-controls button').forEach(b=>b.classList.toggle('active',b===btn));renderJournal(btn.dataset.filter)}));
const dialog=document.querySelector('#addDialog');document.querySelector('#openAdd').addEventListener('click',()=>dialog.showModal());document.querySelector('#closeAdd').addEventListener('click',()=>dialog.close());
function compressImage(file){return new Promise(resolve=>{if(!file)return resolve(null);const reader=new FileReader();reader.onload=()=>{const image=new Image();image.onload=()=>{const max=900,scale=Math.min(1,max/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=image.width*scale;canvas.height=image.height*scale;canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.72))};image.src=reader.result};reader.readAsDataURL(file)})}
document.querySelector('#ideaForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form);if(!data.get('title'))return;const photo=await compressImage(data.get('photo')?.size?data.get('photo'):null),saved=stored(),item={title:data.get('title'),category:data.get('category'),month:data.get('month'),body:data.get('note'),fragile:data.get('fragile')==='on',photo,createdAt:new Date().toISOString()};saved.push(item);try{localStorage.setItem('anushka-ideas',JSON.stringify(saved))}catch{item.photo=null;localStorage.setItem('anushka-ideas',JSON.stringify(saved));showToast('Idea planted; the image was too large to store')}dialog.close();form.reset();plantSavedIdeas();renderJournal();showToast(`“${item.title}” has been planted`)});
document.querySelector('#nurtureBtn').addEventListener('click',()=>{if(!current)return;const idea=ideas[current];idea.health=Math.min(100,idea.health+12);idea.status=idea.health>55?'Growing':'Recovering';document.querySelector('#statusText').textContent=idea.status;document.querySelector('#statusFill').style.width=idea.health+'%';const ring=document.querySelector(`[data-id="${current}"] .care-ring`);if(ring)ring.style.borderColor='#65805a';renderJournal();showToast('Care added — this idea feels stronger')});
